name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      run: |
        yarn install
        yarn run build

    # Upload builds
    - uses: actions/upload-artifact@v2
      with:
        path: extension/*
